# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=False, max_length=100),
        ),
    ]
