# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_friend_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='users',
        ),
    ]
