# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171101_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users',
            new_name='user',
        ),
    ]
