# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171101_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
    ]
