# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171102_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomments',
            name='post_associated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
        ),
    ]
