# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20171102_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomments',
            name='post_associated',
        ),
        migrations.AddField(
            model_name='mycomments',
            name='post_associated',
            field=models.ManyToManyField(to='accounts.Post'),
        ),
    ]
