# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20171102_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomments',
            name='post_associated',
        ),
        migrations.AddField(
            model_name='mycomments',
            name='post_associated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
        ),
    ]
