"""
Django settings for ThePortal project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!!jfp$&p7_vh_z30fm0c7stf#$6c)g2r41fs711udcu25sf3b)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'social_django',
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    #'ThePortal.middleware.LoginRequiredMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'ThePortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'ThePortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = 'os.path.join(BASE_DIR)'

LOGIN_REDIRECT_URL = '/accounts/profile/'

LOGIN_URL = '/accounts/login/'

LOGIN_EXEMPT_URLS =(
    r'https://github.com/login?client_id=fb6ab34e877f0a28d32f&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3Dfb6ab34e877f0a28d32f%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8000%252Foauth%252Fcomplete%252Fgithub%252F%253Fredirect_state%253DTQOCSsqyUWfiZxLiOgKTwJ9O4EWiqSXq%26response_type%3Dcode%26state%3DTQOCSsqyUWfiZxLiOgKTwJ9O4EWiqSXq/$',
    r'https://www.facebook.com/login.php?skip_api_login=1&api_key=125076774841978&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.10%2Fdialog%2Foauth%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8000%252Foauth%252Fcomplete%252Ffacebook%252F%253Fredirect_state%253DXbuF7MpWzaLpgTcl7sMNDjLW58J8ellF%26state%3DXbuF7MpWzaLpgTcl7sMNDjLW58J8ellF%26return_scopes%3Dtrue%26client_id%3D125076774841978%26ret%3Dlogin%26logger_id%3D95ba5975-feb6-8068-72ce-a59f567a77fc&cancel_url=http%3A%2F%2Flocalhost%3A8000%2Foauth%2Fcomplete%2Ffacebook%2F%3Fredirect_state%3DXbuF7MpWzaLpgTcl7sMNDjLW58J8ellF%26error%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3DXbuF7MpWzaLpgTcl7sMNDjLW58J8ellF%23_%3D_&display=page&locale=en_GB&logger_id=95ba5975-feb6-8068-72ce-a59f567a77fc/$',
    r'^accounts/login/#_=_/$',
    r'^accounts/index/$',
    r'^accounts/logout/$',
    r'^accounts/register/$',
    r'^oauth/login/github/$',
    r'^oauth/login/facebook/$',
)

LOGOUT_URL = '/accounts/index'

SOCIAL_AUTH_GITHUB_KEY = 'fb6ab34e877f0a28d32f'
SOCIAL_AUTH_GITHUB_SECRET = 'bdf7df284e879801f0f1392d9f54c4722c62c7d6'

SOCIAL_AUTH_FACEBOOK_KEY = '125076774841978'
SOCIAL_AUTH_FACEBOOK_SECRET = '7358388deaf40098e8a7a8b43b5a84af'

EMAIL_HOST = 'localhost'
